# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone X"
])

languages([
  "de-DE", "es-ES", "it-IT", "en-US", "fr-FR"
])

# The name of the scheme which contains the UI Tests
scheme "L10nSnapshotsTests"
