#!/bin/sh
# Copyright (c) 2014, Angelo Haller
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

set -e

usage () {
  echo "Usage: [VARIABLE...] $(basename $0) framework libname"
  echo "  framework   Name of the framework to create"
  echo "  libname     Name of the .a library"
  echo ""
  echo "  VARIABLEs are:"
  echo "    ARCHS     Only build for specific architectures. Default is:"
  echo "                armv7|armv7s|arm64|i686|x86_64"
  echo "    PREFIX    Installation prefix for framework and static files."
  echo ""
  echo "  All additional parameters are passed to the configure script."
  exit 1
}

# Sanity checks
if [ "$#" -lt 2 ]; then
  usage
fi

ICONFIGURE="$(pwd)/iconfigure"

FRAMEWORK=$1
LIBARCHIVE=$2

shift 2

# if [ -z "$PREFIX" ]; then
  PREFIX="$(pwd)"
# fi

STATICDIR="$PREFIX/Static"
FRAMEWORKDIR="$PREFIX/Frameworks/$FRAMEWORK.framework"

if [ -z "$ARCHS" ]; then
  ARCHS="i386 x86_64 armv7 armv7s arm64"
fi

# Build all architectures
for ARCH in $ARCHS; do
  make distclean || true
  PREFIX="$STATICDIR/$ARCH" $ICONFIGURE $ARCH $@
  make
  make install
done

# Install header files
PREFIX="$STATICDIR/$ARCH" $ICONFIGURE $ARCH --includedir="$FRAMEWORKDIR/Headers" $@
make
make install

# Create multiarch archive
LIPOARCHS=""
for ARCH in $ARCHS; do
  LIPOARCHS="$LIPOARCHS -arch $ARCH $STATICDIR/$ARCH/lib/$LIBARCHIVE"
done
lipo -create $LIPOARCHS -output "Frameworks/$LIBARCHIVE"

echo "Success!"
echo "Built $FRAMEWORK for architectures: $ARCHS"
