#!/bin/sh

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/. */

npm -v
NPM_INSTALLED=$(echo $?)

if [ ! $NPM_INSTALLED == 0 ];
then
  echo "NPM required to update and install datastore"
  exit 1
fi

rm -rf lockbox-ios/lockbox-datastore/bundle.js

git clone git@github.com:mozilla-lockbox/lockbox-datastore.git

cd lockbox-datastore

npm install
npm install -g browserify
browserify lib/index.js -s DataStoreModule -o bundle.js

mv bundle.js ../lockbox-ios/lockbox-datastore/bundle.js

cd ..
rm -rf lockbox-datastore/
